with Whole_Project_Behavioral_Tests;
with BTree_Invariants_Tests;
with Free_List_Manager_Tests;
with Record_Serializer_Tests;
with Page_Parser_Tests;
with WAL_Frame_Parser_Tests;
with Checksum_Tests;
with Storage_Page_Tests;
with Record_Format_Tests;
with File_IO_Tests;
with Persistent_Table_Tests;
with Index_Tests;
with Secondary_Index_Tests;
with Migration_Tests;
with Query_Tests;
with Concurrency_Tests;
with Maintenance_Tests;
with Release_Hardening_Tests;
with Optimizer_Tests;
with MVCC_Tests;
with WAL_Tests;
with Relational_Features_Tests;
with Full_Text_Tests;
with Backup_Restore_Tests;
with Encryption_Tests;
with Extension_Tests;
with Type_System_Tests;
with Observability_Tests;
with Hardening_Tests;
with Registry_Ownership_Tests;
with Whole_Project_Integration_Tests;
with Support_Package_Tests;

package body Database_Test_Suite is
   function Suite return AUnit.Test_Suites.Access_Test_Suite is
      S : constant AUnit.Test_Suites.Access_Test_Suite := new AUnit.Test_Suites.Test_Suite;
   begin
      S.Add_Test (new Storage_Page_Tests.Case_Type);
      S.Add_Test (new Record_Format_Tests.Case_Type);
      S.Add_Test (new File_IO_Tests.Case_Type);
      S.Add_Test (new Index_Tests.Case_Type);
      S.Add_Test (new Secondary_Index_Tests.Case_Type);
      S.Add_Test (new Migration_Tests.Case_Type);
      S.Add_Test (new Query_Tests.Case_Type);
      S.Add_Test (new Concurrency_Tests.Case_Type);
      S.Add_Test (new Persistent_Table_Tests.Case_Type);
      S.Add_Test (new Maintenance_Tests.Case_Type);
      S.Add_Test (new Release_Hardening_Tests.Case_Type);
      S.Add_Test (new Optimizer_Tests.Case_Type);
      S.Add_Test (new MVCC_Tests.Case_Type);
      S.Add_Test (new WAL_Tests.Case_Type);
      S.Add_Test (new Relational_Features_Tests.Case_Type);
      S.Add_Test (new Full_Text_Tests.Case_Type);
      S.Add_Test (new Backup_Restore_Tests.Case_Type);
      S.Add_Test (new Encryption_Tests.Case_Type);
      S.Add_Test (new Extension_Tests.Case_Type);
      S.Add_Test (new Type_System_Tests.Case_Type);
      S.Add_Test (new Observability_Tests.Case_Type);
      S.Add_Test (new Hardening_Tests.Case_Type);
      S.Add_Test (new Registry_Ownership_Tests.Case_Type);
      S.Add_Test (new Whole_Project_Integration_Tests.Case_Type);
      S.Add_Test (new Support_Package_Tests.Case_Type);
      S.Add_Test (new Checksum_Tests.Case_Type);
      S.Add_Test (new WAL_Frame_Parser_Tests.Case_Type);
      S.Add_Test (new Page_Parser_Tests.Case_Type);
      S.Add_Test (new Record_Serializer_Tests.Case_Type);
      S.Add_Test (new Free_List_Manager_Tests.Case_Type);
      S.Add_Test (new BTree_Invariants_Tests.Case_Type);
      S.Add_Test (new Whole_Project_Behavioral_Tests.Case_Type);

      return S;
   end Suite;
end Database_Test_Suite;
